import React from "react";
import Link from "next/link";
import styles from "./register.module.css"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <div id={styles.login_dialog}>
        <Link href="/" id={styles.quit}></Link>
        <div>
          {children}
        </div>
      </div>
      </body>
    </html>
  )
}
