import StoryProgress from "./StoryProgress";

const meta = {
  component: StoryProgress,
  argTypes: {},
};

export default meta;

const parts1 = [
  {
    lang: "en",
    type: "CHALLENGE_PROMPT",
    editor: {
      end_no: 51,
      start_no: 49,
      active_no: 50,
      block_start_no: 49,
    },
    prompt: {
      text: "Tap what you hear. CONTINUATION",
      hints: [],
      hintMap: [],
    },
    trackingProperties: {
      line_index: 0,
      challenge_type: "continuation",
    },
  },
  {
    lang: "nl",
    line: {
      type: "CHARACTER",
      content: {
        text: "I write with words.",
        audio: {
          ssml: {
            id: 0,
            text: '<speak>I write with <prosody volume="silent">words</prosody>.</speak>',
            mapping: [
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              0,
              1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              12,
              12,
              12,
              12,
              12,
              12,
              12,
              12,
              12,
              12,
              12,
              12,
              12,
              12,
              12,
              12,
              12,
              12,
              12,
              12,
              12,
              12,
              12,
              12,
              12,
              13,
              14,
              15,
              16,
              17,
              17,
              17,
              17,
              17,
              17,
              17,
              17,
              17,
              17,
              17,
              18,
              18,
              18,
              18,
              18,
              18,
              18,
              18,
              18,
            ],
            speaker: "",
            plan_text: "I write with [words].",
            inser_index: 7,
          },
        },
        hints: ["I", "write", "with", "words."],
        hintMap: [
          {
            rangeTo: 0,
            hintIndex: 0,
            rangeFrom: 0,
          },
          {
            rangeTo: 6,
            hintIndex: 1,
            rangeFrom: 2,
          },
          {
            rangeTo: 11,
            hintIndex: 2,
            rangeFrom: 8,
          },
          {
            rangeTo: 17,
            hintIndex: 3,
            rangeFrom: 13,
          },
        ],
        lang_hints: "en",
      },
      avatarUrl:
        "https://stories-cdn.duolingo.com/image/2b2b64afe0c2af19eed8ac69c36cb8803d0a090e.svg",
      characterId: 560,
    },
    type: "LINE",
    audio: {
      ssml: {
        id: 0,
        text: '<speak>I write with <prosody volume="silent">words</prosody>.</speak>',
        mapping: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          0,
          1,
          2,
          3,
          4,
          5,
          6,
          7,
          8,
          9,
          10,
          11,
          12,
          12,
          12,
          12,
          12,
          12,
          12,
          12,
          12,
          12,
          12,
          12,
          12,
          12,
          12,
          12,
          12,
          12,
          12,
          12,
          12,
          12,
          12,
          12,
          12,
          12,
          13,
          14,
          15,
          16,
          17,
          17,
          17,
          17,
          17,
          17,
          17,
          17,
          17,
          17,
          17,
          18,
          18,
          18,
          18,
          18,
          18,
          18,
          18,
          18,
        ],
        speaker: "",
        plan_text: "I write with [words].",
        inser_index: 7,
      },
    },
    editor: {
      end_no: 53,
      start_no: 51,
    },
    trackingProperties: {
      line_index: 0,
    },
    hideRangesForChallenge: [
      {
        end: 18,
        start: 13,
      },
    ],
  },
  {
    lang: "nl",
    type: "MULTIPLE_CHOICE",
    editor: {
      end_no: 60,
      start_no: 53,
    },
    answers: [
      {
        text: "words",
        hints: ["words"],
        hintMap: [
          {
            rangeTo: 4,
            hintIndex: 0,
            rangeFrom: 0,
          },
        ],
        lang_hints: "en",
      },
      {
        text: "sentences",
        hints: ["sentences"],
        hintMap: [
          {
            rangeTo: 8,
            hintIndex: 0,
            rangeFrom: 0,
          },
        ],
        lang_hints: "en",
      },
      {
        text: "texts",
        hints: ["texts"],
        hintMap: [
          {
            rangeTo: 4,
            hintIndex: 0,
            rangeFrom: 0,
          },
        ],
        lang_hints: "en",
      },
    ],
    correctAnswerIndex: 0,
    trackingProperties: {
      line_index: 0,
      challenge_type: "continuation",
    },
  },
];

const parts2 = [
  {
    line: {
      type: "CHARACTER",
      content: {
        text: "Wat?",
        audio: {
          url: "audio/56/00ae35fc.mp3",
          ssml: {
            id: 56,
            text: "<speak>Wat?</speak>",
            speaker: "nl-NL-MaartenNeural(pitch=high)",
            plan_text: "Wat?",
            inser_index: 20,
            plan_text_speaker_name: "nl-NL-MaartenNeural(pitch=high)",
          },
          keypoints: [
            {
              rangeEnd: 3,
              audioStart: 50,
            },
          ],
        },
        hints: ["What"],
        hintMap: [
          {
            rangeTo: 2,
            hintIndex: 0,
            rangeFrom: 0,
          },
        ],
      },
      avatarUrl:
        "https://stories-cdn.duolingo.com/image/9ed7124d96bbf015b7b8d9c62ddd6abba98d29c4.svg",
      characterId: 100,
    },
    type: "LINE",
    audio: {
      url: "audio/56/00ae35fc.mp3",
      ssml: {
        id: 56,
        text: "<speak>Wat?</speak>",
        speaker: "nl-NL-MaartenNeural(pitch=high)",
        plan_text: "Wat?",
        inser_index: 20,
        plan_text_speaker_name: "nl-NL-MaartenNeural(pitch=high)",
      },
      keypoints: [
        {
          rangeEnd: 3,
          audioStart: 50,
        },
      ],
    },
    editor: {
      end_no: 126,
      start_no: 121,
      active_no: 122,
      block_start_no: 121,
    },
    trackingProperties: {
      line_index: 1,
    },
    hideRangesForChallenge: [],
  },
  {
    type: "MULTIPLE_CHOICE",
    editor: {
      end_no: 131,
      start_no: 126,
      active_no: 127,
      block_start_no: 126,
    },
    answers: [
      {
        text: "Yes, that's true.",
        hints: [],
        hintMap: [],
      },
      {
        text: "No, that's not right.",
        hints: [],
        hintMap: [],
      },
    ],
    question: {
      text: "Paul en Julie zitten allebei met de verkeerde persoon aan tafel.",
      hints: [],
      hintMap: [],
    },
    correctAnswerIndex: 0,
    trackingProperties: {
      line_index: 1,
      challenge_type: "multiple-choice",
    },
  },
];

const part_list = [
  {
    lang: "nl",
    type: "HEADER",
    audio: {
      ssml: {
        id: 0,
        text: "<speak>This is the Title</speak>",
        mapping: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          0,
          1,
          2,
          3,
          4,
          5,
          6,
          7,
          8,
          9,
          10,
          11,
          12,
          13,
          14,
          15,
          16,
          16,
          16,
          16,
          16,
          16,
          16,
          16,
          16,
        ],
        speaker: "",
        plan_text: "This is the Title",
        inser_index: 0,
      },
    },
    editor: {
      end_no: 13,
      start_no: 8,
      active_no: 9,
      block_start_no: 8,
    },
    illustrationUrl:
      "https://stories-cdn.duolingo.com/image/783305780a6dad8e0e4eb34109d948e6a5fc2c35.svg",
    trackingProperties: {},
    learningLanguageTitleContent: {
      text: "This is the Title",
      audio: {
        ssml: {
          id: 0,
          text: "<speak>This is the Title</speak>",
          mapping: [
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            0,
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11,
            12,
            13,
            14,
            15,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
          ],
          speaker: "",
          plan_text: "This is the Title",
          inser_index: 0,
        },
      },
      hints: ["Thes", "is", "the", "Title"],
      hintMap: [
        {
          rangeTo: 3,
          hintIndex: 0,
          rangeFrom: 0,
        },
        {
          rangeTo: 6,
          hintIndex: 1,
          rangeFrom: 5,
        },
        {
          rangeTo: 10,
          hintIndex: 2,
          rangeFrom: 8,
        },
        {
          rangeTo: 16,
          hintIndex: 3,
          rangeFrom: 12,
        },
      ],
      lang_hints: "en",
    },
  },
  {
    lang: "nl",
    line: {
      type: "PROSE",
      content: {
        text: "A narrator line.",
        audio: {
          ssml: {
            id: 0,
            text: "<speak>A narrator line.</speak>",
            mapping: [
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              0,
              1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13,
              14,
              15,
              15,
              15,
              15,
              15,
              15,
              15,
              15,
              15,
            ],
            speaker: "",
            plan_text: "A narrator line.",
            inser_index: 1,
          },
        },
        hints: ["A", "narrator", "line."],
        hintMap: [
          {
            rangeTo: 0,
            hintIndex: 0,
            rangeFrom: 0,
          },
          {
            rangeTo: 9,
            hintIndex: 1,
            rangeFrom: 2,
          },
          {
            rangeTo: 14,
            hintIndex: 2,
            rangeFrom: 11,
          },
        ],
        lang_hints: "en",
      },
    },
    type: "LINE",
    audio: {
      ssml: {
        id: 0,
        text: "<speak>A narrator line.</speak>",
        mapping: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          0,
          1,
          2,
          3,
          4,
          5,
          6,
          7,
          8,
          9,
          10,
          11,
          12,
          13,
          14,
          15,
          15,
          15,
          15,
          15,
          15,
          15,
          15,
          15,
        ],
        speaker: "",
        plan_text: "A narrator line.",
        inser_index: 1,
      },
    },
    editor: {
      end_no: 17,
      start_no: 13,
      active_no: 14,
      block_start_no: 13,
    },
    trackingProperties: {
      line_index: 1,
    },
    hideRangesForChallenge: [],
  },
  {
    lang: "nl",
    line: {
      type: "CHARACTER",
      content: {
        text: "Hello, I am a speaker!",
        audio: {
          ssml: {
            id: 0,
            text: "<speak>Hello, I am a speaker!</speak>",
            mapping: [
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              0,
              1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13,
              14,
              15,
              16,
              17,
              18,
              19,
              20,
              21,
              21,
              21,
              21,
              21,
              21,
              21,
              21,
              21,
            ],
            speaker: "",
            plan_text: "Hello, I am a speaker!",
            inser_index: 2,
          },
        },
        hints: ["Hello,", "I", "am", "a", "speaker!"],
        hintMap: [
          {
            rangeTo: 4,
            hintIndex: 0,
            rangeFrom: 0,
          },
          {
            rangeTo: 7,
            hintIndex: 1,
            rangeFrom: 7,
          },
          {
            rangeTo: 10,
            hintIndex: 2,
            rangeFrom: 9,
          },
          {
            rangeTo: 12,
            hintIndex: 3,
            rangeFrom: 12,
          },
          {
            rangeTo: 20,
            hintIndex: 4,
            rangeFrom: 14,
          },
        ],
        lang_hints: "en",
      },
      avatarUrl:
        "https://stories-cdn.duolingo.com/image/7074d00522c0be6307e3e405f503699a99d2121e.svg",
      characterId: 593,
    },
    type: "LINE",
    audio: {
      ssml: {
        id: 0,
        text: "<speak>Hello, I am a speaker!</speak>",
        mapping: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          0,
          1,
          2,
          3,
          4,
          5,
          6,
          7,
          8,
          9,
          10,
          11,
          12,
          13,
          14,
          15,
          16,
          17,
          18,
          19,
          20,
          21,
          21,
          21,
          21,
          21,
          21,
          21,
          21,
          21,
        ],
        speaker: "",
        plan_text: "Hello, I am a speaker!",
        inser_index: 2,
      },
    },
    editor: {
      end_no: 21,
      start_no: 17,
      active_no: 18,
      block_start_no: 17,
    },
    trackingProperties: {
      line_index: 2,
    },
    hideRangesForChallenge: [],
  },
  {
    lang: "nl",
    line: {
      type: "CHARACTER",
      content: {
        text: "I am another speaker!",
        audio: {
          ssml: {
            id: 0,
            text: "<speak>I am another speaker!</speak>",
            mapping: [
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              0,
              1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13,
              14,
              15,
              16,
              17,
              18,
              19,
              20,
              20,
              20,
              20,
              20,
              20,
              20,
              20,
              20,
            ],
            speaker: "",
            plan_text: "I am another speaker!",
            inser_index: 3,
          },
        },
        hints: ["I", "am", "another", "speaker!"],
        hintMap: [
          {
            rangeTo: 0,
            hintIndex: 0,
            rangeFrom: 0,
          },
          {
            rangeTo: 3,
            hintIndex: 1,
            rangeFrom: 2,
          },
          {
            rangeTo: 11,
            hintIndex: 2,
            rangeFrom: 5,
          },
          {
            rangeTo: 19,
            hintIndex: 3,
            rangeFrom: 13,
          },
        ],
        lang_hints: "en",
      },
      avatarUrl:
        "https://stories-cdn.duolingo.com/image/2b2b64afe0c2af19eed8ac69c36cb8803d0a090e.svg",
      characterId: 560,
    },
    type: "LINE",
    audio: {
      ssml: {
        id: 0,
        text: "<speak>I am another speaker!</speak>",
        mapping: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          0,
          1,
          2,
          3,
          4,
          5,
          6,
          7,
          8,
          9,
          10,
          11,
          12,
          13,
          14,
          15,
          16,
          17,
          18,
          19,
          20,
          20,
          20,
          20,
          20,
          20,
          20,
          20,
          20,
        ],
        speaker: "",
        plan_text: "I am another speaker!",
        inser_index: 3,
      },
    },
    editor: {
      end_no: 25,
      start_no: 21,
      active_no: 22,
      block_start_no: 21,
    },
    trackingProperties: {
      line_index: 3,
    },
    hideRangesForChallenge: [],
  },
  {
    lang: "en",
    type: "MULTIPLE_CHOICE",
    editor: {
      end_no: 30,
      start_no: 25,
      active_no: 26,
      block_start_no: 25,
    },
    answers: [
      {
        text: "Right answers start with a +",
        hints: [],
        hintMap: [],
      },
      {
        text: "negative answers with a -      yes  I need   to go to work",
        hints: [],
        hintMap: [],
      },
    ],
    question: {
      text: "Do you know how MULTIPLE_CHOICE works?",
      hints: [],
      hintMap: [],
    },
    correctAnswerIndex: 0,
    trackingProperties: {
      line_index: 3,
      challenge_type: "multiple-choice",
    },
  },
  {
    lang: "en",
    type: "CHALLENGE_PROMPT",
    editor: {
      end_no: 32,
      start_no: 30,
      active_no: 31,
      block_start_no: 30,
    },
    prompt: {
      text: "Tap what you hear. The ARRANGE question uses () to create text buttons.",
      hints: [],
      hintMap: [],
    },
    trackingProperties: {
      line_index: 4,
      challenge_type: "arrange",
    },
  },
  {
    lang: "nl",
    line: {
      type: "CHARACTER",
      content: {
        text: "First second third",
        audio: {
          ssml: {
            id: 0,
            text: "<speak>First second third</speak>",
            mapping: [
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              0,
              1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13,
              14,
              15,
              16,
              17,
              17,
              17,
              17,
              17,
              17,
              17,
              17,
              17,
            ],
            speaker: "",
            plan_text: "[(First) (second) (third)]",
            inser_index: 4,
          },
        },
        hints: ["First", "Second", "Third"],
        hintMap: [
          {
            rangeTo: 4,
            hintIndex: 0,
            rangeFrom: 0,
          },
          {
            rangeTo: 11,
            hintIndex: 1,
            rangeFrom: 6,
          },
          {
            rangeTo: 17,
            hintIndex: 2,
            rangeFrom: 13,
          },
        ],
        lang_hints: "en",
      },
      avatarUrl:
        "https://stories-cdn.duolingo.com/image/7074d00522c0be6307e3e405f503699a99d2121e.svg",
      characterId: 593,
    },
    type: "LINE",
    audio: {
      ssml: {
        id: 0,
        text: "<speak>First second third</speak>",
        mapping: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          0,
          1,
          2,
          3,
          4,
          5,
          6,
          7,
          8,
          9,
          10,
          11,
          12,
          13,
          14,
          15,
          16,
          17,
          17,
          17,
          17,
          17,
          17,
          17,
          17,
          17,
        ],
        speaker: "",
        plan_text: "[(First) (second) (third)]",
        inser_index: 4,
      },
    },
    editor: {
      end_no: 35,
      start_no: 32,
    },
    trackingProperties: {
      line_index: 4,
    },
    hideRangesForChallenge: [
      {
        end: 18,
        start: 0,
      },
    ],
  },
  {
    lang: "nl",
    type: "ARRANGE",
    editor: {
      end_no: 35,
      start_no: 32,
    },
    phraseOrder: [1, 0, 2],
    selectablePhrases: ["second", "First", "third"],
    characterPositions: [6, 13, 18],
    trackingProperties: {
      line_index: 4,
      challenge_type: "arrange",
    },
  },
  {
    lang: "nl",
    line: {
      type: "CHARACTER",
      content: {
        text: "The right word has a plus symbol.",
        audio: {
          ssml: {
            id: 0,
            text: "<speak>The right word has a plus symbol.</speak>",
            mapping: [
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              0,
              1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13,
              14,
              15,
              16,
              17,
              18,
              19,
              20,
              21,
              22,
              23,
              24,
              25,
              26,
              27,
              28,
              29,
              30,
              31,
              32,
              32,
              32,
              32,
              32,
              32,
              32,
              32,
              32,
            ],
            speaker: "",
            plan_text: "The (+right) (word) has a plus (symbol).",
            inser_index: 5,
          },
        },
        hints: ["sorry", "my", "love", "I am", "tired", "I work", "a lot"],
        hintMap: [
          {
            rangeTo: 2,
            hintIndex: 0,
            rangeFrom: 0,
          },
          {
            rangeTo: 8,
            hintIndex: 1,
            rangeFrom: 4,
          },
          {
            rangeTo: 13,
            hintIndex: 2,
            rangeFrom: 10,
          },
          {
            rangeTo: 17,
            hintIndex: 3,
            rangeFrom: 15,
          },
          {
            rangeTo: 19,
            hintIndex: 4,
            rangeFrom: 19,
          },
          {
            rangeTo: 24,
            hintIndex: 5,
            rangeFrom: 21,
          },
          {
            rangeTo: 31,
            hintIndex: 6,
            rangeFrom: 26,
          },
        ],
        lang_hints: "en",
      },
      avatarUrl:
        "https://stories-cdn.duolingo.com/image/2b2b64afe0c2af19eed8ac69c36cb8803d0a090e.svg",
      characterId: 560,
    },
    type: "LINE",
    audio: {
      ssml: {
        id: 0,
        text: "<speak>The right word has a plus symbol.</speak>",
        mapping: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          0,
          1,
          2,
          3,
          4,
          5,
          6,
          7,
          8,
          9,
          10,
          11,
          12,
          13,
          14,
          15,
          16,
          17,
          18,
          19,
          20,
          21,
          22,
          23,
          24,
          25,
          26,
          27,
          28,
          29,
          30,
          31,
          32,
          32,
          32,
          32,
          32,
          32,
          32,
          32,
          32,
        ],
        speaker: "",
        plan_text: "The (+right) (word) has a plus (symbol).",
        inser_index: 5,
      },
    },
    editor: {
      end_no: 37,
      start_no: 35,
      active_no: 36,
      block_start_no: 35,
    },
    trackingProperties: {
      line_index: 5,
    },
    hideRangesForChallenge: [],
  },
  {
    lang: "nl",
    type: "POINT_TO_PHRASE",
    editor: {
      end_no: 40,
      start_no: 37,
    },
    question: {
      text: 'Choose the option that means "right". In the POINT_TO_PHRASE',
      hints: [],
      hintMap: [],
    },
    lang_question: "en",
    transcriptParts: [
      {
        text: "The",
        selectable: false,
      },
      {
        text: " ",
        selectable: false,
      },
      {
        text: "right",
        selectable: true,
      },
      {
        text: " ",
        selectable: false,
      },
      {
        text: "word",
        selectable: true,
      },
      {
        text: " ",
        selectable: false,
      },
      {
        text: "has",
        selectable: false,
      },
      {
        text: " ",
        selectable: false,
      },
      {
        text: "a",
        selectable: false,
      },
      {
        text: " ",
        selectable: false,
      },
      {
        text: "plus",
        selectable: false,
      },
      {
        text: " ",
        selectable: false,
      },
      {
        text: "symbol",
        selectable: true,
      },
      {
        text: ".",
        selectable: false,
      },
    ],
    correctAnswerIndex: 0,
    trackingProperties: {
      line_index: 5,
      challenge_type: "point-to-phrase",
    },
  },
  {
    lang: "en",
    type: "CHALLENGE_PROMPT",
    editor: {
      end_no: 42,
      start_no: 40,
      active_no: 41,
      block_start_no: 40,
    },
    prompt: {
      text: "Choose the best answer: The SELECT_PHRASE has similar answers.",
      hints: [],
      hintMap: [],
    },
    trackingProperties: {
      line_index: 6,
      challenge_type: "select-phrases",
    },
  },
  {
    lang: "nl",
    line: {
      type: "CHARACTER",
      content: {
        text: "What is the right  word?",
        audio: {
          url: "audio/56/ddacf426.mp3",
          ssml: {
            id: 0,
            text: "<speak>What is the right  word?</speak>",
            mapping: [
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              0,
              1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13,
              14,
              15,
              16,
              17,
              18,
              19,
              20,
              21,
              22,
              23,
              23,
              23,
              23,
              23,
              23,
              23,
              23,
              23,
            ],
            speaker: "",
            plan_text: "What is the right  [word]?",
            inser_index: 6,
          },
          keypoints: [
            {
              rangeEnd: 3,
              audioStart: 50,
            },
            {
              rangeEnd: 6,
              audioStart: 275,
            },
            {
              rangeEnd: 10,
              audioStart: 400,
            },
            {
              rangeEnd: 19,
              audioStart: 500,
            },
          ],
        },
        hints: ["What", "is", "the", "right", "word"],
        hintMap: [
          {
            rangeTo: 3,
            hintIndex: 0,
            rangeFrom: 0,
          },
          {
            rangeTo: 6,
            hintIndex: 1,
            rangeFrom: 5,
          },
          {
            rangeTo: 10,
            hintIndex: 2,
            rangeFrom: 8,
          },
          {
            rangeTo: 16,
            hintIndex: 3,
            rangeFrom: 12,
          },
          {
            rangeTo: 22,
            hintIndex: 4,
            rangeFrom: 19,
          },
        ],
        lang_hints: "en",
      },
      avatarUrl:
        "https://stories-cdn.duolingo.com/image/7074d00522c0be6307e3e405f503699a99d2121e.svg",
      characterId: 593,
    },
    type: "LINE",
    audio: {
      url: "audio/56/ddacf426.mp3",
      ssml: {
        id: 0,
        text: "<speak>What is the right  word?</speak>",
        mapping: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          0,
          1,
          2,
          3,
          4,
          5,
          6,
          7,
          8,
          9,
          10,
          11,
          12,
          13,
          14,
          15,
          16,
          17,
          18,
          19,
          20,
          21,
          22,
          23,
          23,
          23,
          23,
          23,
          23,
          23,
          23,
          23,
        ],
        speaker: "",
        plan_text: "What is the right  [word]?",
        inser_index: 6,
      },
      keypoints: [
        {
          rangeEnd: 3,
          audioStart: 50,
        },
        {
          rangeEnd: 6,
          audioStart: 275,
        },
        {
          rangeEnd: 10,
          audioStart: 400,
        },
        {
          rangeEnd: 19,
          audioStart: 500,
        },
      ],
    },
    editor: {
      end_no: 45,
      start_no: 42,
    },
    trackingProperties: {
      line_index: 6,
    },
    hideRangesForChallenge: [
      {
        end: 23,
        start: 19,
      },
    ],
  },
  {
    lang: "nl",
    type: "SELECT_PHRASE",
    editor: {
      end_no: 49,
      start_no: 45,
    },
    answers: ["word", "bird", "skirt"],
    correctAnswerIndex: 0,
    trackingProperties: {
      line_index: 6,
      challenge_type: "select-phrases",
    },
  },
  {
    lang: "en",
    type: "CHALLENGE_PROMPT",
    editor: {
      end_no: 51,
      start_no: 49,
      active_no: 50,
      block_start_no: 49,
    },
    prompt: {
      text: "Tap what you hear. CONTINUATION",
      hints: [],
      hintMap: [],
    },
    trackingProperties: {
      line_index: 7,
      challenge_type: "continuation",
    },
  },
  {
    lang: "nl",
    line: {
      type: "CHARACTER",
      content: {
        text: "I write with words.",
        audio: {
          ssml: {
            id: 0,
            text: '<speak>I write with <prosody volume="silent">words</prosody>.</speak>',
            mapping: [
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              0,
              1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              12,
              12,
              12,
              12,
              12,
              12,
              12,
              12,
              12,
              12,
              12,
              12,
              12,
              12,
              12,
              12,
              12,
              12,
              12,
              12,
              12,
              12,
              12,
              12,
              12,
              13,
              14,
              15,
              16,
              17,
              17,
              17,
              17,
              17,
              17,
              17,
              17,
              17,
              17,
              17,
              18,
              18,
              18,
              18,
              18,
              18,
              18,
              18,
              18,
            ],
            speaker: "",
            plan_text: "I write with [words].",
            inser_index: 7,
          },
        },
        hints: ["I", "write", "with", "words."],
        hintMap: [
          {
            rangeTo: 0,
            hintIndex: 0,
            rangeFrom: 0,
          },
          {
            rangeTo: 6,
            hintIndex: 1,
            rangeFrom: 2,
          },
          {
            rangeTo: 11,
            hintIndex: 2,
            rangeFrom: 8,
          },
          {
            rangeTo: 17,
            hintIndex: 3,
            rangeFrom: 13,
          },
        ],
        lang_hints: "en",
      },
      avatarUrl:
        "https://stories-cdn.duolingo.com/image/2b2b64afe0c2af19eed8ac69c36cb8803d0a090e.svg",
      characterId: 560,
    },
    type: "LINE",
    audio: {
      ssml: {
        id: 0,
        text: '<speak>I write with <prosody volume="silent">words</prosody>.</speak>',
        mapping: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          0,
          1,
          2,
          3,
          4,
          5,
          6,
          7,
          8,
          9,
          10,
          11,
          12,
          12,
          12,
          12,
          12,
          12,
          12,
          12,
          12,
          12,
          12,
          12,
          12,
          12,
          12,
          12,
          12,
          12,
          12,
          12,
          12,
          12,
          12,
          12,
          12,
          12,
          13,
          14,
          15,
          16,
          17,
          17,
          17,
          17,
          17,
          17,
          17,
          17,
          17,
          17,
          17,
          18,
          18,
          18,
          18,
          18,
          18,
          18,
          18,
          18,
        ],
        speaker: "",
        plan_text: "I write with [words].",
        inser_index: 7,
      },
    },
    editor: {
      end_no: 53,
      start_no: 51,
    },
    trackingProperties: {
      line_index: 7,
    },
    hideRangesForChallenge: [
      {
        end: 18,
        start: 13,
      },
    ],
  },
  {
    lang: "nl",
    type: "MULTIPLE_CHOICE",
    editor: {
      end_no: 60,
      start_no: 53,
    },
    answers: [
      {
        text: "words",
        hints: ["words"],
        hintMap: [
          {
            rangeTo: 4,
            hintIndex: 0,
            rangeFrom: 0,
          },
        ],
        lang_hints: "en",
      },
      {
        text: "sentences",
        hints: ["sentences"],
        hintMap: [
          {
            rangeTo: 8,
            hintIndex: 0,
            rangeFrom: 0,
          },
        ],
        lang_hints: "en",
      },
      {
        text: "texts",
        hints: ["texts"],
        hintMap: [
          {
            rangeTo: 4,
            hintIndex: 0,
            rangeFrom: 0,
          },
        ],
        lang_hints: "en",
      },
    ],
    correctAnswerIndex: 0,
    trackingProperties: {
      line_index: 7,
      challenge_type: "continuation",
    },
  },
  {
    lang: "nl",
    type: "MATCH",
    editor: {
      end_no: 69,
      start_no: 60,
      active_no: 61,
      block_start_no: 60,
    },
    prompt: "Tap the pairs",
    fallbackHints: [
      {
        phrase: "A",
        translation: "1",
      },
      {
        phrase: "B",
        translation: "2",
      },
      {
        phrase: "C",
        translation: "3",
      },
      {
        phrase: "D",
        translation: "4",
      },
      {
        phrase: "E",
        translation: "5",
      },
    ],
    lang_question: "en",
    trackingProperties: {
      line_index: 8,
      challenge_type: "match",
    },
  },
];

export const Normal = {
  render: (args) => {
    const story = { elements: part_list };
    const parts = [];
    let last_id = -1;
    for (let element of story.elements) {
      if (element.trackingProperties === undefined) {
        continue;
      }
      if (last_id !== element.trackingProperties.line_index) {
        parts.push([]);
        last_id = element.trackingProperties.line_index;
      }
      parts[parts.length - 1].push(element);
    }
    return <StoryProgress parts_list={parts} {...args}></StoryProgress>;
  },
};
