/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as Privacy_policyRouteImport } from './routes/privacy_policy'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CourseIdRouteImport } from './routes/$courseId'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EditorIndexRouteImport } from './routes/editor.index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as StoryStoryIdRouteImport } from './routes/story/$storyId'
import { Route as DocsSplatRouteImport } from './routes/docs.$'
import { Route as DevStoryFooterButtonTestRouteImport } from './routes/dev.story-footer-button-test'
import { Route as AuthSigninRouteImport } from './routes/auth/signin'
import { Route as AuthReset_pwRouteImport } from './routes/auth/reset_pw'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthEditorRouteImport } from './routes/auth/editor'
import { Route as AuthAdminRouteImport } from './routes/auth/admin'
import { Route as AudioVoicesRouteImport } from './routes/audio/voices'
import { Route as AudioUploadRouteImport } from './routes/audio/upload'
import { Route as AudioElevenlabs_quotaRouteImport } from './routes/audio.elevenlabs_quota'
import { Route as AudioCreateRouteImport } from './routes/audio/create'
import { Route as ApiOgStoryRouteImport } from './routes/api/og-story'
import { Route as ApiOgCourseRouteImport } from './routes/api/og-course'
import { Route as ApiOgRouteImport } from './routes/api/og'
import { Route as AdminLanguagesRouteImport } from './routes/admin.languages'
import { Route as AdminCoursesRouteImport } from './routes/admin.courses'
import { Route as AdminUsersIndexRouteImport } from './routes/admin.users.index'
import { Route as AdminStoryIndexRouteImport } from './routes/admin.story.index'
import { Route as StoryStoryIdTestRouteImport } from './routes/story/$storyId/test'
import { Route as StoryStoryIdScriptRouteImport } from './routes/story/$storyId/script'
import { Route as StoryStoryIdAuto_playRouteImport } from './routes/story/$storyId/auto_play'
import { Route as EditorStoryStoryIdRouteImport } from './routes/editor.story.$storyId'
import { Route as EditorLocalizationLanguageRouteImport } from './routes/editor.localization.$language'
import { Route as EditorLanguageLanguageRouteImport } from './routes/editor.language.$language'
import { Route as EditorCourseCourseIdRouteImport } from './routes/editor.course.$courseId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin.users.$userId'
import { Route as AdminStoryStoryIdRouteImport } from './routes/admin.story.$storyId'
import { Route as EditorLanguageLanguageTts_editRouteImport } from './routes/editor.language.$language.tts_edit'
import { Route as EditorCourseCourseIdVoicesRouteImport } from './routes/editor.course.$courseId.voices'
import { Route as EditorCourseCourseIdLocalizationRouteImport } from './routes/editor.course.$courseId.localization'
import { Route as EditorCourseCourseIdVoicesEditRouteImport } from './routes/editor.course.$courseId.voices.edit'
import { Route as EditorCourseCourseIdStoryStoryIdRouteImport } from './routes/editor.course.$courseId.story.$storyId'
import { Route as EditorCourseCourseIdImportFromIdRouteImport } from './routes/editor.course.$courseId.import.$fromId'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const Privacy_policyRoute = Privacy_policyRouteImport.update({
  id: '/privacy_policy',
  path: '/privacy_policy',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseIdRoute = CourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorIndexRoute = EditorIndexRouteImport.update({
  id: '/editor/',
  path: '/editor/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryStoryIdRoute = StoryStoryIdRouteImport.update({
  id: '/story/$storyId',
  path: '/story/$storyId',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DevStoryFooterButtonTestRoute =
  DevStoryFooterButtonTestRouteImport.update({
    id: '/dev/story-footer-button-test',
    path: '/dev/story-footer-button-test',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthReset_pwRoute = AuthReset_pwRouteImport.update({
  id: '/auth/reset_pw',
  path: '/auth/reset_pw',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthEditorRoute = AuthEditorRouteImport.update({
  id: '/auth/editor',
  path: '/auth/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAdminRoute = AuthAdminRouteImport.update({
  id: '/auth/admin',
  path: '/auth/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioVoicesRoute = AudioVoicesRouteImport.update({
  id: '/audio/voices',
  path: '/audio/voices',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioUploadRoute = AudioUploadRouteImport.update({
  id: '/audio/upload',
  path: '/audio/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioElevenlabs_quotaRoute = AudioElevenlabs_quotaRouteImport.update({
  id: '/audio/elevenlabs_quota',
  path: '/audio/elevenlabs_quota',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioCreateRoute = AudioCreateRouteImport.update({
  id: '/audio/create',
  path: '/audio/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgStoryRoute = ApiOgStoryRouteImport.update({
  id: '/api/og-story',
  path: '/api/og-story',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgCourseRoute = ApiOgCourseRouteImport.update({
  id: '/api/og-course',
  path: '/api/og-course',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgRoute = ApiOgRouteImport.update({
  id: '/api/og',
  path: '/api/og',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLanguagesRoute = AdminLanguagesRouteImport.update({
  id: '/admin/languages',
  path: '/admin/languages',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/admin/courses',
  path: '/admin/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/admin/users/',
  path: '/admin/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStoryIndexRoute = AdminStoryIndexRouteImport.update({
  id: '/admin/story/',
  path: '/admin/story/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryStoryIdTestRoute = StoryStoryIdTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => StoryStoryIdRoute,
} as any)
const StoryStoryIdScriptRoute = StoryStoryIdScriptRouteImport.update({
  id: '/script',
  path: '/script',
  getParentRoute: () => StoryStoryIdRoute,
} as any)
const StoryStoryIdAuto_playRoute = StoryStoryIdAuto_playRouteImport.update({
  id: '/auto_play',
  path: '/auto_play',
  getParentRoute: () => StoryStoryIdRoute,
} as any)
const EditorStoryStoryIdRoute = EditorStoryStoryIdRouteImport.update({
  id: '/editor/story/$storyId',
  path: '/editor/story/$storyId',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorLocalizationLanguageRoute =
  EditorLocalizationLanguageRouteImport.update({
    id: '/editor/localization/$language',
    path: '/editor/localization/$language',
    getParentRoute: () => rootRouteImport,
  } as any)
const EditorLanguageLanguageRoute = EditorLanguageLanguageRouteImport.update({
  id: '/editor/language/$language',
  path: '/editor/language/$language',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorCourseCourseIdRoute = EditorCourseCourseIdRouteImport.update({
  id: '/editor/course/$courseId',
  path: '/editor/course/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/admin/users/$userId',
  path: '/admin/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStoryStoryIdRoute = AdminStoryStoryIdRouteImport.update({
  id: '/admin/story/$storyId',
  path: '/admin/story/$storyId',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorLanguageLanguageTts_editRoute =
  EditorLanguageLanguageTts_editRouteImport.update({
    id: '/tts_edit',
    path: '/tts_edit',
    getParentRoute: () => EditorLanguageLanguageRoute,
  } as any)
const EditorCourseCourseIdVoicesRoute =
  EditorCourseCourseIdVoicesRouteImport.update({
    id: '/voices',
    path: '/voices',
    getParentRoute: () => EditorCourseCourseIdRoute,
  } as any)
const EditorCourseCourseIdLocalizationRoute =
  EditorCourseCourseIdLocalizationRouteImport.update({
    id: '/localization',
    path: '/localization',
    getParentRoute: () => EditorCourseCourseIdRoute,
  } as any)
const EditorCourseCourseIdVoicesEditRoute =
  EditorCourseCourseIdVoicesEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => EditorCourseCourseIdVoicesRoute,
  } as any)
const EditorCourseCourseIdStoryStoryIdRoute =
  EditorCourseCourseIdStoryStoryIdRouteImport.update({
    id: '/story/$storyId',
    path: '/story/$storyId',
    getParentRoute: () => EditorCourseCourseIdRoute,
  } as any)
const EditorCourseCourseIdImportFromIdRoute =
  EditorCourseCourseIdImportFromIdRouteImport.update({
    id: '/import/$fromId',
    path: '/import/$fromId',
    getParentRoute: () => EditorCourseCourseIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$courseId': typeof CourseIdRoute
  '/faq': typeof FaqRoute
  '/learn': typeof LearnRoute
  '/privacy_policy': typeof Privacy_policyRoute
  '/profile': typeof ProfileRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/languages': typeof AdminLanguagesRoute
  '/api/og': typeof ApiOgRoute
  '/api/og-course': typeof ApiOgCourseRoute
  '/api/og-story': typeof ApiOgStoryRoute
  '/audio/create': typeof AudioCreateRoute
  '/audio/elevenlabs_quota': typeof AudioElevenlabs_quotaRoute
  '/audio/upload': typeof AudioUploadRoute
  '/audio/voices': typeof AudioVoicesRoute
  '/auth/admin': typeof AuthAdminRoute
  '/auth/editor': typeof AuthEditorRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset_pw': typeof AuthReset_pwRoute
  '/auth/signin': typeof AuthSigninRoute
  '/dev/story-footer-button-test': typeof DevStoryFooterButtonTestRoute
  '/docs/$': typeof DocsSplatRoute
  '/story/$storyId': typeof StoryStoryIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/editor/': typeof EditorIndexRoute
  '/admin/story/$storyId': typeof AdminStoryStoryIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/editor/course/$courseId': typeof EditorCourseCourseIdRouteWithChildren
  '/editor/language/$language': typeof EditorLanguageLanguageRouteWithChildren
  '/editor/localization/$language': typeof EditorLocalizationLanguageRoute
  '/editor/story/$storyId': typeof EditorStoryStoryIdRoute
  '/story/$storyId/auto_play': typeof StoryStoryIdAuto_playRoute
  '/story/$storyId/script': typeof StoryStoryIdScriptRoute
  '/story/$storyId/test': typeof StoryStoryIdTestRoute
  '/admin/story/': typeof AdminStoryIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/editor/course/$courseId/localization': typeof EditorCourseCourseIdLocalizationRoute
  '/editor/course/$courseId/voices': typeof EditorCourseCourseIdVoicesRouteWithChildren
  '/editor/language/$language/tts_edit': typeof EditorLanguageLanguageTts_editRoute
  '/editor/course/$courseId/import/$fromId': typeof EditorCourseCourseIdImportFromIdRoute
  '/editor/course/$courseId/story/$storyId': typeof EditorCourseCourseIdStoryStoryIdRoute
  '/editor/course/$courseId/voices/edit': typeof EditorCourseCourseIdVoicesEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$courseId': typeof CourseIdRoute
  '/faq': typeof FaqRoute
  '/learn': typeof LearnRoute
  '/privacy_policy': typeof Privacy_policyRoute
  '/profile': typeof ProfileRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/languages': typeof AdminLanguagesRoute
  '/api/og': typeof ApiOgRoute
  '/api/og-course': typeof ApiOgCourseRoute
  '/api/og-story': typeof ApiOgStoryRoute
  '/audio/create': typeof AudioCreateRoute
  '/audio/elevenlabs_quota': typeof AudioElevenlabs_quotaRoute
  '/audio/upload': typeof AudioUploadRoute
  '/audio/voices': typeof AudioVoicesRoute
  '/auth/admin': typeof AuthAdminRoute
  '/auth/editor': typeof AuthEditorRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset_pw': typeof AuthReset_pwRoute
  '/auth/signin': typeof AuthSigninRoute
  '/dev/story-footer-button-test': typeof DevStoryFooterButtonTestRoute
  '/docs/$': typeof DocsSplatRoute
  '/story/$storyId': typeof StoryStoryIdRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/docs': typeof DocsIndexRoute
  '/editor': typeof EditorIndexRoute
  '/admin/story/$storyId': typeof AdminStoryStoryIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/editor/course/$courseId': typeof EditorCourseCourseIdRouteWithChildren
  '/editor/language/$language': typeof EditorLanguageLanguageRouteWithChildren
  '/editor/localization/$language': typeof EditorLocalizationLanguageRoute
  '/editor/story/$storyId': typeof EditorStoryStoryIdRoute
  '/story/$storyId/auto_play': typeof StoryStoryIdAuto_playRoute
  '/story/$storyId/script': typeof StoryStoryIdScriptRoute
  '/story/$storyId/test': typeof StoryStoryIdTestRoute
  '/admin/story': typeof AdminStoryIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/editor/course/$courseId/localization': typeof EditorCourseCourseIdLocalizationRoute
  '/editor/course/$courseId/voices': typeof EditorCourseCourseIdVoicesRouteWithChildren
  '/editor/language/$language/tts_edit': typeof EditorLanguageLanguageTts_editRoute
  '/editor/course/$courseId/import/$fromId': typeof EditorCourseCourseIdImportFromIdRoute
  '/editor/course/$courseId/story/$storyId': typeof EditorCourseCourseIdStoryStoryIdRoute
  '/editor/course/$courseId/voices/edit': typeof EditorCourseCourseIdVoicesEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$courseId': typeof CourseIdRoute
  '/faq': typeof FaqRoute
  '/learn': typeof LearnRoute
  '/privacy_policy': typeof Privacy_policyRoute
  '/profile': typeof ProfileRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/languages': typeof AdminLanguagesRoute
  '/api/og': typeof ApiOgRoute
  '/api/og-course': typeof ApiOgCourseRoute
  '/api/og-story': typeof ApiOgStoryRoute
  '/audio/create': typeof AudioCreateRoute
  '/audio/elevenlabs_quota': typeof AudioElevenlabs_quotaRoute
  '/audio/upload': typeof AudioUploadRoute
  '/audio/voices': typeof AudioVoicesRoute
  '/auth/admin': typeof AuthAdminRoute
  '/auth/editor': typeof AuthEditorRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset_pw': typeof AuthReset_pwRoute
  '/auth/signin': typeof AuthSigninRoute
  '/dev/story-footer-button-test': typeof DevStoryFooterButtonTestRoute
  '/docs/$': typeof DocsSplatRoute
  '/story/$storyId': typeof StoryStoryIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/editor/': typeof EditorIndexRoute
  '/admin/story/$storyId': typeof AdminStoryStoryIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/editor/course/$courseId': typeof EditorCourseCourseIdRouteWithChildren
  '/editor/language/$language': typeof EditorLanguageLanguageRouteWithChildren
  '/editor/localization/$language': typeof EditorLocalizationLanguageRoute
  '/editor/story/$storyId': typeof EditorStoryStoryIdRoute
  '/story/$storyId/auto_play': typeof StoryStoryIdAuto_playRoute
  '/story/$storyId/script': typeof StoryStoryIdScriptRoute
  '/story/$storyId/test': typeof StoryStoryIdTestRoute
  '/admin/story/': typeof AdminStoryIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/editor/course/$courseId/localization': typeof EditorCourseCourseIdLocalizationRoute
  '/editor/course/$courseId/voices': typeof EditorCourseCourseIdVoicesRouteWithChildren
  '/editor/language/$language/tts_edit': typeof EditorLanguageLanguageTts_editRoute
  '/editor/course/$courseId/import/$fromId': typeof EditorCourseCourseIdImportFromIdRoute
  '/editor/course/$courseId/story/$storyId': typeof EditorCourseCourseIdStoryStoryIdRoute
  '/editor/course/$courseId/voices/edit': typeof EditorCourseCourseIdVoicesEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$courseId'
    | '/faq'
    | '/learn'
    | '/privacy_policy'
    | '/profile'
    | '/admin/courses'
    | '/admin/languages'
    | '/api/og'
    | '/api/og-course'
    | '/api/og-story'
    | '/audio/create'
    | '/audio/elevenlabs_quota'
    | '/audio/upload'
    | '/audio/voices'
    | '/auth/admin'
    | '/auth/editor'
    | '/auth/register'
    | '/auth/reset_pw'
    | '/auth/signin'
    | '/dev/story-footer-button-test'
    | '/docs/$'
    | '/story/$storyId'
    | '/admin/'
    | '/docs/'
    | '/editor/'
    | '/admin/story/$storyId'
    | '/admin/users/$userId'
    | '/api/auth/$'
    | '/editor/course/$courseId'
    | '/editor/language/$language'
    | '/editor/localization/$language'
    | '/editor/story/$storyId'
    | '/story/$storyId/auto_play'
    | '/story/$storyId/script'
    | '/story/$storyId/test'
    | '/admin/story/'
    | '/admin/users/'
    | '/editor/course/$courseId/localization'
    | '/editor/course/$courseId/voices'
    | '/editor/language/$language/tts_edit'
    | '/editor/course/$courseId/import/$fromId'
    | '/editor/course/$courseId/story/$storyId'
    | '/editor/course/$courseId/voices/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$courseId'
    | '/faq'
    | '/learn'
    | '/privacy_policy'
    | '/profile'
    | '/admin/courses'
    | '/admin/languages'
    | '/api/og'
    | '/api/og-course'
    | '/api/og-story'
    | '/audio/create'
    | '/audio/elevenlabs_quota'
    | '/audio/upload'
    | '/audio/voices'
    | '/auth/admin'
    | '/auth/editor'
    | '/auth/register'
    | '/auth/reset_pw'
    | '/auth/signin'
    | '/dev/story-footer-button-test'
    | '/docs/$'
    | '/story/$storyId'
    | '/admin'
    | '/docs'
    | '/editor'
    | '/admin/story/$storyId'
    | '/admin/users/$userId'
    | '/api/auth/$'
    | '/editor/course/$courseId'
    | '/editor/language/$language'
    | '/editor/localization/$language'
    | '/editor/story/$storyId'
    | '/story/$storyId/auto_play'
    | '/story/$storyId/script'
    | '/story/$storyId/test'
    | '/admin/story'
    | '/admin/users'
    | '/editor/course/$courseId/localization'
    | '/editor/course/$courseId/voices'
    | '/editor/language/$language/tts_edit'
    | '/editor/course/$courseId/import/$fromId'
    | '/editor/course/$courseId/story/$storyId'
    | '/editor/course/$courseId/voices/edit'
  id:
    | '__root__'
    | '/'
    | '/$courseId'
    | '/faq'
    | '/learn'
    | '/privacy_policy'
    | '/profile'
    | '/admin/courses'
    | '/admin/languages'
    | '/api/og'
    | '/api/og-course'
    | '/api/og-story'
    | '/audio/create'
    | '/audio/elevenlabs_quota'
    | '/audio/upload'
    | '/audio/voices'
    | '/auth/admin'
    | '/auth/editor'
    | '/auth/register'
    | '/auth/reset_pw'
    | '/auth/signin'
    | '/dev/story-footer-button-test'
    | '/docs/$'
    | '/story/$storyId'
    | '/admin/'
    | '/docs/'
    | '/editor/'
    | '/admin/story/$storyId'
    | '/admin/users/$userId'
    | '/api/auth/$'
    | '/editor/course/$courseId'
    | '/editor/language/$language'
    | '/editor/localization/$language'
    | '/editor/story/$storyId'
    | '/story/$storyId/auto_play'
    | '/story/$storyId/script'
    | '/story/$storyId/test'
    | '/admin/story/'
    | '/admin/users/'
    | '/editor/course/$courseId/localization'
    | '/editor/course/$courseId/voices'
    | '/editor/language/$language/tts_edit'
    | '/editor/course/$courseId/import/$fromId'
    | '/editor/course/$courseId/story/$storyId'
    | '/editor/course/$courseId/voices/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CourseIdRoute: typeof CourseIdRoute
  FaqRoute: typeof FaqRoute
  LearnRoute: typeof LearnRoute
  Privacy_policyRoute: typeof Privacy_policyRoute
  ProfileRoute: typeof ProfileRoute
  AdminCoursesRoute: typeof AdminCoursesRoute
  AdminLanguagesRoute: typeof AdminLanguagesRoute
  ApiOgRoute: typeof ApiOgRoute
  ApiOgCourseRoute: typeof ApiOgCourseRoute
  ApiOgStoryRoute: typeof ApiOgStoryRoute
  AudioCreateRoute: typeof AudioCreateRoute
  AudioElevenlabs_quotaRoute: typeof AudioElevenlabs_quotaRoute
  AudioUploadRoute: typeof AudioUploadRoute
  AudioVoicesRoute: typeof AudioVoicesRoute
  AuthAdminRoute: typeof AuthAdminRoute
  AuthEditorRoute: typeof AuthEditorRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthReset_pwRoute: typeof AuthReset_pwRoute
  AuthSigninRoute: typeof AuthSigninRoute
  DevStoryFooterButtonTestRoute: typeof DevStoryFooterButtonTestRoute
  DocsSplatRoute: typeof DocsSplatRoute
  StoryStoryIdRoute: typeof StoryStoryIdRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  DocsIndexRoute: typeof DocsIndexRoute
  EditorIndexRoute: typeof EditorIndexRoute
  AdminStoryStoryIdRoute: typeof AdminStoryStoryIdRoute
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  EditorCourseCourseIdRoute: typeof EditorCourseCourseIdRouteWithChildren
  EditorLanguageLanguageRoute: typeof EditorLanguageLanguageRouteWithChildren
  EditorLocalizationLanguageRoute: typeof EditorLocalizationLanguageRoute
  EditorStoryStoryIdRoute: typeof EditorStoryStoryIdRoute
  AdminStoryIndexRoute: typeof AdminStoryIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy_policy': {
      id: '/privacy_policy'
      path: '/privacy_policy'
      fullPath: '/privacy_policy'
      preLoaderRoute: typeof Privacy_policyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$courseId': {
      id: '/$courseId'
      path: '/$courseId'
      fullPath: '/$courseId'
      preLoaderRoute: typeof CourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/': {
      id: '/editor/'
      path: '/editor'
      fullPath: '/editor/'
      preLoaderRoute: typeof EditorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story/$storyId': {
      id: '/story/$storyId'
      path: '/story/$storyId'
      fullPath: '/story/$storyId'
      preLoaderRoute: typeof StoryStoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/story-footer-button-test': {
      id: '/dev/story-footer-button-test'
      path: '/dev/story-footer-button-test'
      fullPath: '/dev/story-footer-button-test'
      preLoaderRoute: typeof DevStoryFooterButtonTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset_pw': {
      id: '/auth/reset_pw'
      path: '/auth/reset_pw'
      fullPath: '/auth/reset_pw'
      preLoaderRoute: typeof AuthReset_pwRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/editor': {
      id: '/auth/editor'
      path: '/auth/editor'
      fullPath: '/auth/editor'
      preLoaderRoute: typeof AuthEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/admin': {
      id: '/auth/admin'
      path: '/auth/admin'
      fullPath: '/auth/admin'
      preLoaderRoute: typeof AuthAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio/voices': {
      id: '/audio/voices'
      path: '/audio/voices'
      fullPath: '/audio/voices'
      preLoaderRoute: typeof AudioVoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio/upload': {
      id: '/audio/upload'
      path: '/audio/upload'
      fullPath: '/audio/upload'
      preLoaderRoute: typeof AudioUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio/elevenlabs_quota': {
      id: '/audio/elevenlabs_quota'
      path: '/audio/elevenlabs_quota'
      fullPath: '/audio/elevenlabs_quota'
      preLoaderRoute: typeof AudioElevenlabs_quotaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio/create': {
      id: '/audio/create'
      path: '/audio/create'
      fullPath: '/audio/create'
      preLoaderRoute: typeof AudioCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og-story': {
      id: '/api/og-story'
      path: '/api/og-story'
      fullPath: '/api/og-story'
      preLoaderRoute: typeof ApiOgStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og-course': {
      id: '/api/og-course'
      path: '/api/og-course'
      fullPath: '/api/og-course'
      preLoaderRoute: typeof ApiOgCourseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og': {
      id: '/api/og'
      path: '/api/og'
      fullPath: '/api/og'
      preLoaderRoute: typeof ApiOgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/languages': {
      id: '/admin/languages'
      path: '/admin/languages'
      fullPath: '/admin/languages'
      preLoaderRoute: typeof AdminLanguagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/admin/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/story/': {
      id: '/admin/story/'
      path: '/admin/story'
      fullPath: '/admin/story/'
      preLoaderRoute: typeof AdminStoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story/$storyId/test': {
      id: '/story/$storyId/test'
      path: '/test'
      fullPath: '/story/$storyId/test'
      preLoaderRoute: typeof StoryStoryIdTestRouteImport
      parentRoute: typeof StoryStoryIdRoute
    }
    '/story/$storyId/script': {
      id: '/story/$storyId/script'
      path: '/script'
      fullPath: '/story/$storyId/script'
      preLoaderRoute: typeof StoryStoryIdScriptRouteImport
      parentRoute: typeof StoryStoryIdRoute
    }
    '/story/$storyId/auto_play': {
      id: '/story/$storyId/auto_play'
      path: '/auto_play'
      fullPath: '/story/$storyId/auto_play'
      preLoaderRoute: typeof StoryStoryIdAuto_playRouteImport
      parentRoute: typeof StoryStoryIdRoute
    }
    '/editor/story/$storyId': {
      id: '/editor/story/$storyId'
      path: '/editor/story/$storyId'
      fullPath: '/editor/story/$storyId'
      preLoaderRoute: typeof EditorStoryStoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/localization/$language': {
      id: '/editor/localization/$language'
      path: '/editor/localization/$language'
      fullPath: '/editor/localization/$language'
      preLoaderRoute: typeof EditorLocalizationLanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/language/$language': {
      id: '/editor/language/$language'
      path: '/editor/language/$language'
      fullPath: '/editor/language/$language'
      preLoaderRoute: typeof EditorLanguageLanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/course/$courseId': {
      id: '/editor/course/$courseId'
      path: '/editor/course/$courseId'
      fullPath: '/editor/course/$courseId'
      preLoaderRoute: typeof EditorCourseCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/admin/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/story/$storyId': {
      id: '/admin/story/$storyId'
      path: '/admin/story/$storyId'
      fullPath: '/admin/story/$storyId'
      preLoaderRoute: typeof AdminStoryStoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/language/$language/tts_edit': {
      id: '/editor/language/$language/tts_edit'
      path: '/tts_edit'
      fullPath: '/editor/language/$language/tts_edit'
      preLoaderRoute: typeof EditorLanguageLanguageTts_editRouteImport
      parentRoute: typeof EditorLanguageLanguageRoute
    }
    '/editor/course/$courseId/voices': {
      id: '/editor/course/$courseId/voices'
      path: '/voices'
      fullPath: '/editor/course/$courseId/voices'
      preLoaderRoute: typeof EditorCourseCourseIdVoicesRouteImport
      parentRoute: typeof EditorCourseCourseIdRoute
    }
    '/editor/course/$courseId/localization': {
      id: '/editor/course/$courseId/localization'
      path: '/localization'
      fullPath: '/editor/course/$courseId/localization'
      preLoaderRoute: typeof EditorCourseCourseIdLocalizationRouteImport
      parentRoute: typeof EditorCourseCourseIdRoute
    }
    '/editor/course/$courseId/voices/edit': {
      id: '/editor/course/$courseId/voices/edit'
      path: '/edit'
      fullPath: '/editor/course/$courseId/voices/edit'
      preLoaderRoute: typeof EditorCourseCourseIdVoicesEditRouteImport
      parentRoute: typeof EditorCourseCourseIdVoicesRoute
    }
    '/editor/course/$courseId/story/$storyId': {
      id: '/editor/course/$courseId/story/$storyId'
      path: '/story/$storyId'
      fullPath: '/editor/course/$courseId/story/$storyId'
      preLoaderRoute: typeof EditorCourseCourseIdStoryStoryIdRouteImport
      parentRoute: typeof EditorCourseCourseIdRoute
    }
    '/editor/course/$courseId/import/$fromId': {
      id: '/editor/course/$courseId/import/$fromId'
      path: '/import/$fromId'
      fullPath: '/editor/course/$courseId/import/$fromId'
      preLoaderRoute: typeof EditorCourseCourseIdImportFromIdRouteImport
      parentRoute: typeof EditorCourseCourseIdRoute
    }
  }
}

interface StoryStoryIdRouteChildren {
  StoryStoryIdAuto_playRoute: typeof StoryStoryIdAuto_playRoute
  StoryStoryIdScriptRoute: typeof StoryStoryIdScriptRoute
  StoryStoryIdTestRoute: typeof StoryStoryIdTestRoute
}

const StoryStoryIdRouteChildren: StoryStoryIdRouteChildren = {
  StoryStoryIdAuto_playRoute: StoryStoryIdAuto_playRoute,
  StoryStoryIdScriptRoute: StoryStoryIdScriptRoute,
  StoryStoryIdTestRoute: StoryStoryIdTestRoute,
}

const StoryStoryIdRouteWithChildren = StoryStoryIdRoute._addFileChildren(
  StoryStoryIdRouteChildren,
)

interface EditorCourseCourseIdVoicesRouteChildren {
  EditorCourseCourseIdVoicesEditRoute: typeof EditorCourseCourseIdVoicesEditRoute
}

const EditorCourseCourseIdVoicesRouteChildren: EditorCourseCourseIdVoicesRouteChildren =
  {
    EditorCourseCourseIdVoicesEditRoute: EditorCourseCourseIdVoicesEditRoute,
  }

const EditorCourseCourseIdVoicesRouteWithChildren =
  EditorCourseCourseIdVoicesRoute._addFileChildren(
    EditorCourseCourseIdVoicesRouteChildren,
  )

interface EditorCourseCourseIdRouteChildren {
  EditorCourseCourseIdLocalizationRoute: typeof EditorCourseCourseIdLocalizationRoute
  EditorCourseCourseIdVoicesRoute: typeof EditorCourseCourseIdVoicesRouteWithChildren
  EditorCourseCourseIdImportFromIdRoute: typeof EditorCourseCourseIdImportFromIdRoute
  EditorCourseCourseIdStoryStoryIdRoute: typeof EditorCourseCourseIdStoryStoryIdRoute
}

const EditorCourseCourseIdRouteChildren: EditorCourseCourseIdRouteChildren = {
  EditorCourseCourseIdLocalizationRoute: EditorCourseCourseIdLocalizationRoute,
  EditorCourseCourseIdVoicesRoute: EditorCourseCourseIdVoicesRouteWithChildren,
  EditorCourseCourseIdImportFromIdRoute: EditorCourseCourseIdImportFromIdRoute,
  EditorCourseCourseIdStoryStoryIdRoute: EditorCourseCourseIdStoryStoryIdRoute,
}

const EditorCourseCourseIdRouteWithChildren =
  EditorCourseCourseIdRoute._addFileChildren(EditorCourseCourseIdRouteChildren)

interface EditorLanguageLanguageRouteChildren {
  EditorLanguageLanguageTts_editRoute: typeof EditorLanguageLanguageTts_editRoute
}

const EditorLanguageLanguageRouteChildren: EditorLanguageLanguageRouteChildren =
  {
    EditorLanguageLanguageTts_editRoute: EditorLanguageLanguageTts_editRoute,
  }

const EditorLanguageLanguageRouteWithChildren =
  EditorLanguageLanguageRoute._addFileChildren(
    EditorLanguageLanguageRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CourseIdRoute: CourseIdRoute,
  FaqRoute: FaqRoute,
  LearnRoute: LearnRoute,
  Privacy_policyRoute: Privacy_policyRoute,
  ProfileRoute: ProfileRoute,
  AdminCoursesRoute: AdminCoursesRoute,
  AdminLanguagesRoute: AdminLanguagesRoute,
  ApiOgRoute: ApiOgRoute,
  ApiOgCourseRoute: ApiOgCourseRoute,
  ApiOgStoryRoute: ApiOgStoryRoute,
  AudioCreateRoute: AudioCreateRoute,
  AudioElevenlabs_quotaRoute: AudioElevenlabs_quotaRoute,
  AudioUploadRoute: AudioUploadRoute,
  AudioVoicesRoute: AudioVoicesRoute,
  AuthAdminRoute: AuthAdminRoute,
  AuthEditorRoute: AuthEditorRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthReset_pwRoute: AuthReset_pwRoute,
  AuthSigninRoute: AuthSigninRoute,
  DevStoryFooterButtonTestRoute: DevStoryFooterButtonTestRoute,
  DocsSplatRoute: DocsSplatRoute,
  StoryStoryIdRoute: StoryStoryIdRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  DocsIndexRoute: DocsIndexRoute,
  EditorIndexRoute: EditorIndexRoute,
  AdminStoryStoryIdRoute: AdminStoryStoryIdRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  EditorCourseCourseIdRoute: EditorCourseCourseIdRouteWithChildren,
  EditorLanguageLanguageRoute: EditorLanguageLanguageRouteWithChildren,
  EditorLocalizationLanguageRoute: EditorLocalizationLanguageRoute,
  EditorStoryStoryIdRoute: EditorStoryStoryIdRoute,
  AdminStoryIndexRoute: AdminStoryIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
