import StoryFinishedScreen from "./StoryFinishedScreen";

const meta = {
  component: StoryFinishedScreen,
  argTypes: {},
};

export default meta;

const story = {
  elements: [
    {
      lang: "nl",
      type: "HEADER",
      audio: {
        ssml: {
          id: 0,
          text: "<speak>Title</speak>",
          mapping: [
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            0,
            1,
            2,
            3,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
          ],
          speaker: "",
          plan_text: "Title",
          inser_index: 0,
        },
      },
      editor: {
        end_no: 12,
        start_no: 8,
        active_no: 9,
        block_start_no: 8,
      },
      illustrationUrl:
        "https://stories-cdn.duolingo.com/image/df24f7756b139f6eda927eb776621b9febe1a3f1.svg",
      trackingProperties: {},
      learningLanguageTitleContent: {
        text: "Title",
        audio: {
          ssml: {
            id: 0,
            text: "<speak>Title</speak>",
            mapping: [
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              0,
              1,
              2,
              3,
              4,
              4,
              4,
              4,
              4,
              4,
              4,
              4,
              4,
            ],
            speaker: "",
            plan_text: "Title",
            inser_index: 0,
          },
        },
        hints: ["Title"],
        hintMap: [
          {
            rangeTo: 4,
            hintIndex: 0,
            rangeFrom: 0,
          },
        ],
        lang_hints: "en",
      },
    },
    {
      lang: "nl",
      line: {
        type: "PROSE",
        content: {
          text: "The one and only text.",
          audio: {
            ssml: {
              id: 0,
              text: "<speak>The one and only text.</speak>",
              mapping: [
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                0,
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                9,
                10,
                11,
                12,
                13,
                14,
                15,
                16,
                17,
                18,
                19,
                20,
                21,
                21,
                21,
                21,
                21,
                21,
                21,
                21,
                21,
              ],
              speaker: "",
              plan_text: "The one and only text.",
              inser_index: 1,
            },
          },
          hints: ["The", "one", "and", "only", "text."],
          hintMap: [
            {
              rangeTo: 2,
              hintIndex: 0,
              rangeFrom: 0,
            },
            {
              rangeTo: 6,
              hintIndex: 1,
              rangeFrom: 4,
            },
            {
              rangeTo: 10,
              hintIndex: 2,
              rangeFrom: 8,
            },
            {
              rangeTo: 15,
              hintIndex: 3,
              rangeFrom: 12,
            },
            {
              rangeTo: 20,
              hintIndex: 4,
              rangeFrom: 17,
            },
          ],
          lang_hints: "en",
        },
      },
      type: "LINE",
      audio: {
        ssml: {
          id: 0,
          text: "<speak>The one and only text.</speak>",
          mapping: [
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            0,
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11,
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
            21,
            21,
            21,
            21,
            21,
            21,
            21,
            21,
            21,
          ],
          speaker: "",
          plan_text: "The one and only text.",
          inser_index: 1,
        },
      },
      editor: {
        end_no: 16,
        start_no: 12,
        active_no: 13,
        block_start_no: 12,
      },
      trackingProperties: {
        line_index: 1,
      },
      hideRangesForChallenge: [],
    },
  ],
  illustrations: {
    active:
      "https://stories-cdn.duolingo.com/image/df24f7756b139f6eda927eb776621b9febe1a3f1.svg",
    gilded:
      "https://stories-cdn.duolingo.com/image/8f5de62e27e14a3e766d60caa1dfbca5a12e6480.svg",
    locked:
      "https://stories-cdn.duolingo.com/image/840c68f130c57fb276085e99fd394517c07f0b68.svg",
  },
  id: 134,
  course_id: 186,
  from_language: "en",
  from_language_id: 1,
  from_language_long: "English",
  from_language_rtl: false,
  from_language_name: "Minimal Example",
  learning_language: "test",
  learning_language_long: "test",
  learning_language_rtl: false,
};

export const Normal = {
  render: (args) => (
    <StoryFinishedScreen story={story} {...args}></StoryFinishedScreen>
  ),
};
