/**
 * French grammar curriculum sequence data.
 *
 * Generated from:
 *   docs/french-grammar-curriculum.md (topic inventory)
 *   docs/french-grammar-sequencing-principles.md (ordering rules)
 *   docs/french-grammar-sequence.md (final sequences)
 *
 * Each level has an independent cycle that repeats indefinitely.
 * The cycle is anchored to a fixed date so all learners at the same level
 * see the same grammar focus in a given week.
 */

export type WeekType = "intro" | "review";
export type GrammarMode = "introduce" | "reinforce" | "deepen";
export type GrammarCategory =
  | "foundation"
  | "verb-form"
  | "verb-constr"
  | "pronoun"
  | "determiner"
  | "modifier"
  | "sentence"
  | "clause"
  | "connector"
  | "expression"
  | "discourse";

export type CurriculumWeek = {
  week: number;
  type: WeekType;
  primary: string | null;
  primaryMode: GrammarMode | null;
  category: GrammarCategory | null;
  secondary: string | null;
  secondaryMode: GrammarMode | null;
  reviewTopics: string[] | null;
};

export type LevelSequence = {
  cycleLength: number;
  weeks: CurriculumWeek[];
};

// ---- A1 — 22 topics, 5 review weeks, 27-week cycle ----

const A1_SEQUENCE: CurriculumWeek[] = [
  {
    week: 1,
    type: "intro",
    primary: "Articles: definite, indefinite, partitive",
    primaryMode: "introduce",
    category: "determiner",
    secondary: null,
    secondaryMode: null,
    reviewTopics: null,
  },
  {
    week: 2,
    type: "intro",
    primary: "Present tense: regular verbs",
    primaryMode: "introduce",
    category: "verb-form",
    secondary: "Articles: definite, indefinite, partitive",
    secondaryMode: "reinforce",
    reviewTopics: null,
  },
  {
    week: 3,
    type: "intro",
    primary: "Être and avoir — full present tense",
    primaryMode: "introduce",
    category: "verb-form",
    secondary: "Present tense: regular verbs",
    secondaryMode: "reinforce",
    reviewTopics: null,
  },
  {
    week: 4,
    type: "intro",
    primary: "Gender and number agreement",
    primaryMode: "introduce",
    category: "modifier",
    secondary: "Articles: definite, indefinite, partitive",
    secondaryMode: "reinforce",
    reviewTopics: null,
  },
  {
    week: 5,
    type: "review",
    primary: null,
    primaryMode: null,
    category: null,
    secondary: null,
    secondaryMode: null,
    reviewTopics: [
      "Articles: definite, indefinite, partitive",
      "Present tense: regular verbs",
      "Être and avoir — full present tense",
      "Gender and number agreement",
    ],
  },
  {
    week: 6,
    type: "intro",
    primary: "Common irregular verbs in present",
    primaryMode: "introduce",
    category: "verb-form",
    secondary: "Être and avoir — full present tense",
    secondaryMode: "reinforce",
    reviewTopics: null,
  },
  {
    week: 7,
    type: "intro",
    primary: "Adjective placement and agreement",
    primaryMode: "introduce",
    category: "modifier",
    secondary: "Gender and number agreement",
    secondaryMode: "reinforce",
    reviewTopics: null,
  },
  {
    week: 8,
    type: "intro",
    primary: "Negation (ne...pas)",
    primaryMode: "introduce",
    category: "sentence",
    secondary: "Common irregular verbs in present",
    secondaryMode: "reinforce",
    reviewTopics: null,
  },
  {
    week: 9,
    type: "intro",
    primary: "Question formation",
    primaryMode: "introduce",
    category: "sentence",
    secondary: "Negation (ne...pas)",
    secondaryMode: "reinforce",
    reviewTopics: null,
  },
  {
    week: 10,
    type: "review",
    primary: null,
    primaryMode: null,
    category: null,
    secondary: null,
    secondaryMode: null,
    reviewTopics: [
      "Common irregular verbs in present",
      "Adjective placement and agreement",
      "Negation (ne...pas)",
      "Question formation",
    ],
  },
  {
    week: 11,
    type: "intro",
    primary: "Interrogative adjectives",
    primaryMode: "introduce",
    category: "determiner",
    secondary: "Question formation",
    secondaryMode: "reinforce",
    reviewTopics: null,
  },
  {
    week: 12,
    type: "intro",
    primary: "Stress pronouns (pronoms toniques)",
    primaryMode: "introduce",
    category: "pronoun",
    secondary: null,
    secondaryMode: null,
    reviewTopics: null,
  },
  {
    week: 13,
    type: "intro",
    primary: "Prepositions of place",
    primaryMode: "introduce",
    category: "expression",
    secondary: "Stress pronouns (pronoms toniques)",
    secondaryMode: "reinforce",
    reviewTopics: null,
  },
  {
    week: 14,
    type: "intro",
    primary: "Possessive adjectives",
    primaryMode: "introduce",
    category: "determiner",
    secondary: "Gender and number agreement",
    secondaryMode: "deepen",
    reviewTopics: null,
  },
  {
    week: 15,
    type: "review",
    primary: null,
    primaryMode: null,
    category: null,
    secondary: null,
    secondaryMode: null,
    reviewTopics: [
      "Interrogative adjectives",
      "Stress pronouns (pronoms toniques)",
      "Prepositions of place",
      "Possessive adjectives",
    ],
  },
  {
    week: 16,
    type: "intro",
    primary: "Prepositions with countries, cities, regions",
    primaryMode: "introduce",
    category: "expression",
    secondary: "Articles: definite, indefinite, partitive",
    secondaryMode: "reinforce",
    reviewTopics: null,
  },
  {
    week: 17,
    type: "intro",
    primary: "Basic adverbs",
    primaryMode: "introduce",
    category: "modifier",
    secondary: null,
    secondaryMode: null,
    reviewTopics: null,
  },
  {
    week: 18,
    type: "intro",
    primary: "Il y a / c'est vs il est",
    primaryMode: "introduce",
    category: "expression",
    secondary: "Être and avoir — full present tense",
    secondaryMode: "reinforce",
    reviewTopics: null,
  },
  {
    week: 19,
    type: "intro",
    primary: "Expressions with avoir",
    primaryMode: "introduce",
    category: "expression",
    secondary: "Il y a / c'est vs il est",
    secondaryMode: "reinforce",
    reviewTopics: null,
  },
  {
    week: 20,
    type: "review",
    primary: null,
    primaryMode: null,
    category: null,
    secondary: null,
    secondaryMode: null,
    reviewTopics: [
      "Prepositions with countries, cities, regions",
      "Basic adverbs",
      "Il y a / c'est vs il est",
      "Expressions with avoir",
    ],
  },
  {
    week: 21,
    type: "intro",
    primary: "Impersonal verbs and constructions",
    primaryMode: "introduce",
    category: "expression",
    secondary: "Expressions with avoir",
    secondaryMode: "reinforce",
    reviewTopics: null,
  },
  {
    week: 22,
    type: "intro",
    primary: "Expressions of quantity",
    primaryMode: "introduce",
    category: "modifier",
    secondary: "Articles: definite, indefinite, partitive",
    secondaryMode: "reinforce",
    reviewTopics: null,
  },
  {
    week: 23,
    type: "intro",
    primary: "Numbers, dates, time expressions",
    primaryMode: "introduce",
    category: "expression",
    secondary: null,
    secondaryMode: null,
    reviewTopics: null,
  },
  {
    week: 24,
    type: "intro",
    primary: "Imperative (basic)",
    primaryMode: "introduce",
    category: "sentence",
    secondary: "Present tense: regular verbs",
    secondaryMode: "reinforce",
    reviewTopics: null,
  },
  {
    week: 25,
    type: "review",
    primary: null,
    primaryMode: null,
    category: null,
    secondary: null,
    secondaryMode: null,
    reviewTopics: [
      "Impersonal verbs and constructions",
      "Expressions of quantity",
      "Numbers, dates, time expressions",
      "Imperative (basic)",
    ],
  },
  {
    week: 26,
    type: "intro",
    primary: "Aller + infinitive (futur proche)",
    primaryMode: "introduce",
    category: "verb-constr",
    secondary: "Common irregular verbs in present",
    secondaryMode: "reinforce",
    reviewTopics: null,
  },
  {
    week: 27,
    type: "intro",
    primary: "Venir de + infinitive (passé récent)",
    primaryMode: "introduce",
    category: "verb-constr",
    secondary: "Aller + infinitive (futur proche)",
    secondaryMode: "reinforce",
    reviewTopics: null,
  },
];

// ---- A2 — 14 topics, 3 review weeks, 17-week cycle ----

const A2_SEQUENCE: CurriculumWeek[] = [
  {
    week: 1,
    type: "intro",
    primary: "Passé composé with avoir",
    primaryMode: "introduce",
    category: "verb-form",
    secondary: "Present tense: regular verbs",
    secondaryMode: "deepen",
    reviewTopics: null,
  },
  {
    week: 2,
    type: "intro",
    primary: "Imparfait",
    primaryMode: "introduce",
    category: "verb-form",
    secondary: "Passé composé with avoir",
    secondaryMode: "reinforce",
    reviewTopics: null,
  },
  {
    week: 3,
    type: "intro",
    primary: "Basic connectors",
    primaryMode: "introduce",
    category: "connector",
    secondary: null,
    secondaryMode: null,
    reviewTopics: null,
  },
  {
    week: 4,
    type: "intro",
    primary: "Passé composé with être",
    primaryMode: "introduce",
    category: "verb-form",
    secondary: "Imparfait",
    secondaryMode: "reinforce",
    reviewTopics: null,
  },
  {
    week: 5,
    type: "review",
    primary: null,
    primaryMode: null,
    category: null,
    secondary: null,
    secondaryMode: null,
    reviewTopics: [
      "Passé composé with avoir",
      "Imparfait",
      "Basic connectors",
      "Passé composé with être",
    ],
  },
  {
    week: 6,
    type: "intro",
    primary: "Demonstrative adjectives",
    primaryMode: "introduce",
    category: "determiner",
    secondary: "Articles: definite, indefinite, partitive",
    secondaryMode: "deepen",
    reviewTopics: null,
  },
  {
    week: 7,
    type: "intro",
    primary: "Indefinite adjectives and pronouns",
    primaryMode: "introduce",
    category: "determiner",
    secondary: "Demonstrative adjectives",
    secondaryMode: "reinforce",
    reviewTopics: null,
  },
  {
    week: 8,
    type: "intro",
    primary: "Reflexive verbs in present tense",
    primaryMode: "introduce",
    category: "verb-form",
    secondary: "Stress pronouns (pronoms toniques)",
    secondaryMode: "deepen",
    reviewTopics: null,
  },
  {
    week: 9,
    type: "intro",
    primary: "Adverb formation in -ment",
    primaryMode: "introduce",
    category: "modifier",
    secondary: "Basic adverbs",
    secondaryMode: "deepen",
    reviewTopics: null,
  },
  {
    week: 10,
    type: "review",
    primary: null,
    primaryMode: null,
    category: null,
    secondary: null,
    secondaryMode: null,
    reviewTopics: [
      "Demonstrative adjectives",
      "Indefinite adjectives and pronouns",
      "Reflexive verbs in present tense",
      "Adverb formation in -ment",
    ],
  },
  {
    week: 11,
    type: "intro",
    primary: "Direct object pronouns",
    primaryMode: "introduce",
    category: "pronoun",
    secondary: "Passé composé with avoir",
    secondaryMode: "reinforce",
    reviewTopics: null,
  },
  {
    week: 12,
    type: "intro",
    primary: "Indirect object pronouns",
    primaryMode: "introduce",
    category: "pronoun",
    secondary: "Direct object pronouns",
    secondaryMode: "reinforce",
    reviewTopics: null,
  },
  {
    week: 13,
    type: "intro",
    primary: "Prepositions with infinitives (à/de)",
    primaryMode: "introduce",
    category: "verb-constr",
    secondary: "Common irregular verbs in present",
    secondaryMode: "deepen",
    reviewTopics: null,
  },
  {
    week: 14,
    type: "intro",
    primary: "Être en train de + infinitive",
    primaryMode: "introduce",
    category: "verb-constr",
    secondary: "Present tense: regular verbs",
    secondaryMode: "deepen",
    reviewTopics: null,
  },
  {
    week: 15,
    type: "review",
    primary: null,
    primaryMode: null,
    category: null,
    secondary: null,
    secondaryMode: null,
    reviewTopics: [
      "Direct object pronouns",
      "Indirect object pronouns",
      "Prepositions with infinitives (à/de)",
      "Être en train de + infinitive",
    ],
  },
  {
    week: 16,
    type: "intro",
    primary: "Depuis / pendant / pour",
    primaryMode: "introduce",
    category: "expression",
    secondary: "Passé composé with avoir",
    secondaryMode: "reinforce",
    reviewTopics: null,
  },
  {
    week: 17,
    type: "intro",
    primary: "Relative pronouns (basic) — qui, que",
    primaryMode: "introduce",
    category: "clause",
    secondary: null,
    secondaryMode: null,
    reviewTopics: null,
  },
];

// ---- B1 — 11 topics, 2 review weeks, 13-week cycle ----

const B1_SEQUENCE: CurriculumWeek[] = [
  {
    week: 1,
    type: "intro",
    primary: "Passive voice",
    primaryMode: "introduce",
    category: "sentence",
    secondary: "Passé composé with être",
    secondaryMode: "deepen",
    reviewTopics: null,
  },
  {
    week: 2,
    type: "intro",
    primary: "Reported speech (discours indirect) — basics",
    primaryMode: "introduce",
    category: "clause",
    secondary: "Question formation",
    secondaryMode: "deepen",
    reviewTopics: null,
  },
  {
    week: 3,
    type: "intro",
    primary: "Cause expressions",
    primaryMode: "introduce",
    category: "connector",
    secondary: "Basic connectors",
    secondaryMode: "deepen",
    reviewTopics: null,
  },
  {
    week: 4,
    type: "intro",
    primary: "Plus-que-parfait",
    primaryMode: "introduce",
    category: "verb-form",
    secondary: "Imparfait",
    secondaryMode: "deepen",
    reviewTopics: null,
  },
  {
    week: 5,
    type: "review",
    primary: null,
    primaryMode: null,
    category: null,
    secondary: null,
    secondaryMode: null,
    reviewTopics: [
      "Passive voice",
      "Reported speech (discours indirect) — basics",
      "Cause expressions",
      "Plus-que-parfait",
    ],
  },
  {
    week: 6,
    type: "intro",
    primary: "Subjonctif présent — formation",
    primaryMode: "introduce",
    category: "verb-form",
    secondary: "Present tense: regular verbs",
    secondaryMode: "deepen",
    reviewTopics: null,
  },
  {
    week: 7,
    type: "intro",
    primary: "Subjonctif — common triggers",
    primaryMode: "introduce",
    category: "verb-form",
    secondary: "Subjonctif présent — formation",
    secondaryMode: "reinforce",
    reviewTopics: null,
  },
  {
    week: 8,
    type: "intro",
    primary: "Conditional sentences (types 1 & 2)",
    primaryMode: "introduce",
    category: "clause",
    secondary: "Futur simple",
    secondaryMode: "deepen",
    reviewTopics: null,
  },
  {
    week: 9,
    type: "intro",
    primary: "Relative pronouns (intermediate) — dont, où",
    primaryMode: "introduce",
    category: "clause",
    secondary: "Relative pronouns (basic) — qui, que",
    secondaryMode: "deepen",
    reviewTopics: null,
  },
  {
    week: 10,
    type: "review",
    primary: null,
    primaryMode: null,
    category: null,
    secondary: null,
    secondaryMode: null,
    reviewTopics: [
      "Subjonctif présent — formation",
      "Subjonctif — common triggers",
      "Conditional sentences (types 1 & 2)",
      "Relative pronouns (intermediate) — dont, où",
    ],
  },
  {
    week: 11,
    type: "intro",
    primary: "Gérondif",
    primaryMode: "introduce",
    category: "verb-constr",
    secondary: "Present tense: regular verbs",
    secondaryMode: "deepen",
    reviewTopics: null,
  },
  {
    week: 12,
    type: "intro",
    primary: "Expressing opinion",
    primaryMode: "introduce",
    category: "expression",
    secondary: "Cause expressions",
    secondaryMode: "reinforce",
    reviewTopics: null,
  },
  {
    week: 13,
    type: "intro",
    primary: "Indirect/embedded questions",
    primaryMode: "introduce",
    category: "clause",
    secondary: "Question formation",
    secondaryMode: "deepen",
    reviewTopics: null,
  },
];

// ---- B2 — 8 topics, 2 review weeks, 10-week cycle ----

const B2_SEQUENCE: CurriculumWeek[] = [
  {
    week: 1,
    type: "intro",
    primary: "Conditionnel passé",
    primaryMode: "introduce",
    category: "verb-form",
    secondary: "Conditional present",
    secondaryMode: "deepen",
    reviewTopics: null,
  },
  {
    week: 2,
    type: "intro",
    primary: "Subjonctif passé",
    primaryMode: "introduce",
    category: "verb-form",
    secondary: "Subjonctif présent — formation",
    secondaryMode: "deepen",
    reviewTopics: null,
  },
  {
    week: 3,
    type: "intro",
    primary: "Concession",
    primaryMode: "introduce",
    category: "connector",
    secondary: "Subjonctif — common triggers",
    secondaryMode: "deepen",
    reviewTopics: null,
  },
  {
    week: 4,
    type: "intro",
    primary: "Conditional sentences (type 3)",
    primaryMode: "introduce",
    category: "clause",
    secondary: "Conditionnel passé",
    secondaryMode: "reinforce",
    reviewTopics: null,
  },
  {
    week: 5,
    type: "review",
    primary: null,
    primaryMode: null,
    category: null,
    secondary: null,
    secondaryMode: null,
    reviewTopics: [
      "Conditionnel passé",
      "Subjonctif passé",
      "Concession",
      "Conditional sentences (type 3)",
    ],
  },
  {
    week: 6,
    type: "intro",
    primary: "Passive voice — advanced",
    primaryMode: "introduce",
    category: "sentence",
    secondary: "Passive voice",
    secondaryMode: "deepen",
    reviewTopics: null,
  },
  {
    week: 7,
    type: "intro",
    primary: "Passé simple — recognition",
    primaryMode: "introduce",
    category: "verb-form",
    secondary: "Passé composé vs imparfait",
    secondaryMode: "deepen",
    reviewTopics: null,
  },
  {
    week: 8,
    type: "intro",
    primary: "Conditionnel journalistique",
    primaryMode: "introduce",
    category: "verb-form",
    secondary: "Conditionnel passé",
    secondaryMode: "reinforce",
    reviewTopics: null,
  },
  {
    week: 9,
    type: "review",
    primary: null,
    primaryMode: null,
    category: null,
    secondary: null,
    secondaryMode: null,
    reviewTopics: [
      "Passive voice — advanced",
      "Passé simple — recognition",
      "Conditionnel journalistique",
    ],
  },
  {
    week: 10,
    type: "intro",
    primary: "Double object pronouns",
    primaryMode: "introduce",
    category: "pronoun",
    secondary: "Direct object pronouns",
    secondaryMode: "deepen",
    reviewTopics: null,
  },
];

// ---- Export ----

export const FRENCH_SEQUENCES: Record<string, LevelSequence> = {
  A1: { cycleLength: 27, weeks: A1_SEQUENCE },
  A2: { cycleLength: 17, weeks: A2_SEQUENCE },
  B1: { cycleLength: 13, weeks: B1_SEQUENCE },
  B2: { cycleLength: 10, weeks: B2_SEQUENCE },
};

/** Anchor date for all cycles (a Monday). Cycles start from this date. */
export const CYCLE_ANCHOR_DATE = "2026-04-06";
